name: nasa_asteroid_tracker
description: "A Flutter app to track near-Earth asteroids using NASA's NeoWs API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  lottie: ^2.6.0
  sensors_plus: ^6.1.1
  vector_math: ^2.1.4
  flutter_compass: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
